import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { env } from 'process';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const mapSrc = `"https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${env.client_id}"`;
  return (
    <html lang="en">
      <head>
        <Script strategy="beforeInteractive" src={mapSrc} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
